Repository kroxylicious/kroxylicious, pull requests merged in 2023-07, with the labels that each got.

#427 Update docs for sample
  README.md
  docs/custom-filters.adoc
Labels: documentation

#437 Document Protocol Filter types and patterns
  docs/custom-filters.adoc
Labels: documentation

#468 Split up README.md into separate files.
  CONTRIBUTORS.md
  DEV_GUIDE.md
  PERFORMANCE.md
  README.md
  RELEASING.md
Labels: documentation

#467 Ensure Metric Registry is clean before/after each MetricIT test
  integrationtests/src/test/java/io/kroxylicious/proxy/MetricsIT.java
Labels: tests

#473 Fix #472: Respect logFrame/logNetwork options
  CHANGELOG.md
  kroxylicious/src/main/java/io/kroxylicious/proxy/BannerLogger.java
  kroxylicious/src/main/java/io/kroxylicious/proxy/KafkaProxy.java
  kroxylicious/src/main/resources/banner.txt
  kroxylicious/src/main/resources/log4j2.properties
  kroxylicious/src/test/java/io/kroxylicious/proxy/BannerLoggerTest.java
  kroxylicious/src/test/java/io/kroxylicious/proxy/BannerSupplierTest.java
  kroxylicious/src/test/java/io/kroxylicious/proxy/FileLinesSupplierTest.java
Labels: bug
