Repository kroxylicious/kroxylicious, pull requests merged in 2023-03, with the labels that each got.

#195 Fix some javadoc warnings
  api/kroxylicious-filter-api/src/main/java/io/kroxylicious/proxy/filter/FilterContributor.java
  api/kroxylicious-filter-api/src/main/java/io/kroxylicious/proxy/filter/KrpcFilterContext.java
  api/kroxylicious-filter-api/src/main/templates/Kproxy/Filter.ftl
  api/kroxylicious-filter-api/src/main/templates/Kproxy/KrpcFilter.ftl
Labels: easy-starter

#210 Generate code for the JSON/Kafka request/response converters
  kroxylicious-multitenant/pom.xml
  kroxylicious-multitenant/src/test/java/io/kroxylicious/proxy/filter/multitenant/MultiTenantTransformationFilterTest.java
  kroxylicious-multitenant/src/test/templates/KafkaApiMessageConverter.ftl
Labels: multitenancy, tests

#213 Add mapping & integration test for DescribeGroups RPC
  integrationtests/src/test/java/io/kroxylicious/proxy/multitenant/MultiTenantIT.java
  kroxylicious-multitenant/src/main/java/io/kroxylicious/proxy/filter/multitenant/MultiTenantTransformationFilter.java
  kroxylicious-multitenant/src/test/resources/io/kroxylicious/proxy/filter/multitenant/DescribeGroups.test.yaml
Labels: multitenancy

#217 Map the GroupId for OffsetFetch and OffsetDelete RPCs for alterConsumerGroupOffsets, deleteConsumerGroupOffsets and onOffsetFetchRequest Admin API calls
  integrationtests/src/test/java/io/kroxylicious/proxy/multitenant/MultiTenantIT.java
  kroxylicious-multitenant/src/main/java/io/kroxylicious/proxy/filter/multitenant/MultiTenantTransformationFilter.java
  kroxylicious-multitenant/src/test/resources/io/kroxylicious/proxy/filter/multitenant/OffsetDelete.test.yaml
  kroxylicious-multitenant/src/test/resources/io/kroxylicious/proxy/filter/multitenant/OffsetFetch.test.yaml
Labels: enhancement, multitenancy
