Repository kroxylicious/kroxylicious, pull requests merged in 2025-10, with the labels that each got.

#2722 fix(ci): doc test workflow should skip japicmp too
  .github/workflows/documentation-tests.yml
Labels: dev/maven

#2732 update strimzi version 0.48.0 and update kafka version 4.1.0 for STs
  kroxylicious-systemtests/pom.xml
  pom.xml
Labels: dependencies

#2733 refactor(metrics): remove deprecated metrics
  CHANGELOG.md
  kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/MetricsIT.java
  kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/filter/oauthbearer/OauthBearerValidationIT.java
  kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/KafkaProxy.java
  kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java
  kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyInitializer.java
  kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java
  kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/codec/KafkaMessageListener.java
  kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/metrics/DownstreamMessageCountingKafkaMessageListener.java
  kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/metrics/UpstreamPayloadSizeMetricRecordingKafkaMessageListener.java
  kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/util/Metrics.java
  kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachineTest.java
  kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/internal/metrics/DownstreamMessageCountingKafkaMessageListenerTest.java
  kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/internal/metrics/UpstreamMessageCountingKafkaMessageListenerTest.java
Labels: lifecycle/removal
