Repository kroxylicious/kroxylicious, pull requests merged in 2025-01, with the labels that each got.

#1699 Operator docker documentation and scripting fixes
  Dockerfile.operator
  kroxylicious-operator/DEV_GUIDE.md
  scripts/build-image.sh
Labels: operator

#1680 docs(aws): aws kms authentication procedures
  docs/modules/record-encryption/aws-kms/con-aws-kms-service-config-identity-ec2-metadata.adoc
  docs/modules/record-encryption/aws-kms/con-aws-kms-service-config-identity-long-term.adoc
  docs/modules/record-encryption/aws-kms/con-aws-kms-service-config.adoc
  docs/modules/record-encryption/aws-kms/con-aws-kms-setup-application-identity-ec2-metadata.adoc
  docs/modules/record-encryption/aws-kms/con-aws-kms-setup-application-identity-long-term.adoc
  docs/modules/record-encryption/aws-kms/con-aws-kms-setup.adoc
  docs/modules/record-encryption/aws-kms/proc-aws-kms-setup-application-identity-ec2-metadata.adoc
  docs/modules/record-encryption/aws-kms/proc-aws-kms-setup-application-identity-long-term.adoc
  docs/modules/record-encryption/proc-configuring-record-encryption-filter.adoc
Labels: documentation, filter: record-encryption

#1643 Improve Encryption DEK co-ordination across threads
  CHANGELOG.md
  kroxylicious-filters/kroxylicious-record-encryption/src/main/java/io/kroxylicious/filter/encryption/dek/Dek.java
  kroxylicious-filters/kroxylicious-record-encryption/src/main/java/io/kroxylicious/filter/encryption/encrypt/EncryptionDekCache.java
  kroxylicious-filters/kroxylicious-record-encryption/src/main/java/io/kroxylicious/filter/encryption/encrypt/InBandEncryptionManager.java
  kroxylicious-filters/kroxylicious-record-encryption/src/test/java/io/kroxylicious/filter/encryption/dek/DekManagerTest.java
  kroxylicious-filters/kroxylicious-record-encryption/src/test/java/io/kroxylicious/filter/encryption/dek/DekTest.java
  kroxylicious-filters/kroxylicious-record-encryption/src/test/java/io/kroxylicious/filter/encryption/encrypt/AsyncKms.java
  kroxylicious-filters/kroxylicious-record-encryption/src/test/java/io/kroxylicious/filter/encryption/encrypt/InBandEncryptionManagerTest.java
Labels: bug, filter: record-encryption

#1709 Cluster-scoped filters
  CHANGELOG.md
  kroxylicious-app/example-proxy-config.yaml
  kroxylicious-app/src/test/resources/proxy-config.yaml
  kroxylicious-integration-test-support/src/main/java/io/kroxylicious/proxy/config/FilterDefinitionBuilder.java
  kroxylicious-integration-test-support/src/main/java/io/kroxylicious/proxy/config/NamedFilterDefinitionBuilder.java
  kroxylicious-integration-test-support/src/test/java/io/kroxylicious/proxy/config/ConfigurationTest.java
  kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/DeprecatedConfigurationIT.java
  kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/FilterIT.java
  kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/InvocationCountingFilterFactory.java
  kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/OutOfBandRequestIT.java
  kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/ProxyRpcTest.java
  kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/SingleFilterFactoryInstanceTest.java
  kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/RecordEncryptionDeserializationCompatibilityIT.java
  kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/RecordEncryptionFilterIT.java
  kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/filter/oauthbearer/OauthBearerValidationIT.java
  kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/filter/validation/JsonSchemaRecordValidationIT.java
  kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/filter/validation/JsonSyntaxRecordValidationIT.java
  kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/filter/validation/ProduceRequestValidationIT.java
  kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/multitenant/BaseMultiTenantIT.java
  kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ClusterCondition.java
  kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ProxyConfigSecret.java
  kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/OperatorMainIT.java
  kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/OperatorTestUtils.java
  kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/ProxyReconcilerIT.java
  kroxylicious-operator/src/test/resources/DerivedResourcesTest/filter-resource-not-found/out-Secret-example.yaml
  kroxylicious-operator/src/test/resources/DerivedResourcesTest/two-filters/out-Secret-example.yaml
  kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/KafkaProxy.java
  kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/bootstrap/FilterChainFactory.java
  kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/Configuration.java
  kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/NamedFilterDefinition.java
  kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/VirtualCluster.java
  kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyInitializer.java
  kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/model/VirtualCluster.java
  kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/KafkaProxyTest.java
  kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/bootstrap/FilterChainFactoryTest.java
  kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/config/ConfigParserTest.java
  kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/config/NamedFilterDefinitionTest.java
  kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/internal/KafkaProxyInitializerTest.java
  kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/internal/config/FeaturesTest.java
  kroxylicious-runtime/src/test/resources/config.yaml
  kroxylicious-sample/sample-proxy-config.yaml
  kroxylicious-sample/src/test/java/io/kroxylicious/sample/SampleFilterIT.java
  kubernetes-examples/filters/multi-tenant/base/kroxylicious/kroxylicious-config.yaml
  kubernetes-examples/filters/record-encryption/base/kroxylicious/kroxylicious-config.yaml
  performance-tests/02-no-filters/config.yaml
  performance-tests/03-transform-filter/config.yaml
  performance-tests/04-record-encryption-filter/config.yaml
Labels: configuration api

#1707 Remove Zookeeper usages from kubernetes examples
  kubernetes-examples/filters/multi-tenant/base/kafka/kafka-persistent.yaml
  kubernetes-examples/filters/record-encryption/base/kafka/kafka-persistent.yaml
  kubernetes-examples/network-topologies/portperbroker_plain/base/kafka/kafka-persistent.yaml
  kubernetes-examples/network-topologies/snirouting_tls/base/kafka/kafka-persistent.yaml
Labels: refactoring

#1723 docs(fix): link fix for vault cross-ref
  docs/modules/record-encryption/hashicorp-vault/con-vault-service-config.adoc
  docs/modules/record-encryption/hashicorp-vault/con-vault-setup.adoc
Labels: documentation

#1729 Manually set RENOVATE_GIT_AUTHOR in renovate configuration
  .github/workflows/renovate.yaml
Labels: build

#1660 Support Configuration for Cipher Suits and Protocols used by Upstream and Downstream
  CHANGELOG.md
  CONTRIBUTORS.md
  kroxylicious-api/src/main/java/io/kroxylicious/proxy/config/tls/AllowDeny.java
  kroxylicious-api/src/main/java/io/kroxylicious/proxy/config/tls/Tls.java
  kroxylicious-api/src/test/java/io/kroxylicious/proxy/config/tls/TlsParseTest.java
  kroxylicious-api/src/test/java/io/kroxylicious/proxy/config/tls/TlsTest.java
  kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/TlsIT.java
  kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/model/DenyCipherSuiteFilter.java
  kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/model/VirtualCluster.java
  kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/model/DenyCipherSuiteFilterTest.java
  kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/model/VirtualClusterTest.java
Labels: enhancement, security, network

#1742 ensure that AWS integration and system tests upgrade localstack lockstep
  .github/renovate.json
  kroxylicious-kms-provider-aws-kms-test-support/src/main/java/io/kroxylicious/kms/provider/aws/kms/AwsKmsTestKmsFacade.java
Labels: build

#1752 Ensure that Vault integration, performance and system test upgrade vault container in lock-step.
  .github/renovate.json
  PERFORMANCE.md
  kroxylicious-kms-provider-hashicorp-vault-test-support/src/main/java/io/kroxylicious/kms/provider/hashicorp/vault/VaultTestKmsFacade.java
  kroxylicious-kms-provider-hashicorp-vault/src/test/java/io/kroxylicious/kms/provider/hashicorp/vault/TestVault.java
  kroxylicious-systemtests/src/main/resources/helm_vault_overrides.yaml
  performance-tests/docker-compose.yaml
Labels: dependencies

#1753 Refactor AWS unit tests to use wiremock rather than hand-rolled HTTP server
  kroxylicious-kms-provider-aws-kms/src/test/java/io/kroxylicious/kms/provider/aws/kms/AwsKmsTest.java
  kroxylicious-kms-provider-aws-kms/src/test/java/io/kroxylicious/kms/provider/aws/kms/AwsV4SigningHttpRequestBuilderTest.java
Labels: tests, refactoring

#1713 Documentation for the Fortanix DSM KMS.
  docs/_assets/attributes.adoc
  docs/_assets/trademarks.adoc
  docs/assemblies/assembly-fortanix-dsm.adoc
  docs/assemblies/assembly-record-encryption-filter.adoc
  docs/modules/record-encryption/aws-kms/con-aws-kms-setup.adoc
  docs/modules/record-encryption/fortanix-dsm/con-fortanix-dsm-key-creation.adoc
  docs/modules/record-encryption/fortanix-dsm/con-fortanix-dsm-service-config.adoc
  docs/modules/record-encryption/fortanix-dsm/con-fortanix-dsm-setup.adoc
  docs/modules/record-encryption/hashicorp-vault/con-vault-setup.adoc
Labels: documentation, KMS

#1757 Fix #1445: Remove deprecated ProduceValidationFilterFactory
  CHANGELOG.md
  kroxylicious-filters/kroxylicious-record-validation/src/main/java/io/kroxylicious/proxy/filter/validation/ProduceValidationFilterFactory.java
  kroxylicious-filters/kroxylicious-record-validation/src/main/resources/META-INF/services/io.kroxylicious.proxy.filter.FilterFactory
  kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/filter/validation/ProduceRequestValidationIT.java
Labels: deprecation

#1758 Fix #1380: Remove deprecated FilterFactoryContext#eventLoop
  CHANGELOG.md
  kroxylicious-api/pom.xml
  kroxylicious-api/src/main/java/io/kroxylicious/proxy/filter/FilterFactoryContext.java
  kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/bootstrap/FilterChainFactory.java
  kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/filter/NettyFilterContext.java
  kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/bootstrap/FilterChainFactoryTest.java
Labels: deprecation

#1722 [docs] TLS protocol and cipher suite controls.
  docs/_assets/attributes.adoc
  docs/modules/configuring/con-configuring-client-connections.adoc
  docs/modules/configuring/con-configuring-target-cluster-connections.adoc
Labels: documentation, security

#1756 Refactor Vault unit tests to use Wiremock too
  kroxylicious-kms-provider-hashicorp-vault/pom.xml
  kroxylicious-kms-provider-hashicorp-vault/src/test/java/io/kroxylicious/kms/provider/hashicorp/vault/VaultKmsTest.java
Labels: tests, refactoring

#1759 Fix #1691: Remove hardcoded project version references from the Operator
  kroxylicious-operator/DEV_GUIDE.md
  kroxylicious-operator/pom.xml
  kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ProxyDeployment.java
  kroxylicious-operator/src/main/resources-filtered/kroxylicious-image.properties
  kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/DerivedResourcesTest.java
  kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/ProxyDeploymentTest.java
  kroxylicious-operator/src/test/resources-filtered/DerivedResourcesTest/filter-resource-not-found/cond-Accepted-foo.yaml
  kroxylicious-operator/src/test/resources-filtered/DerivedResourcesTest/filter-resource-not-found/in-Filter-filter-one.yaml
  kroxylicious-operator/src/test/resources-filtered/DerivedResourcesTest/filter-resource-not-found/in-Filter-filter-two.yaml
  kroxylicious-operator/src/test/resources-filtered/DerivedResourcesTest/filter-resource-not-found/in-KafkaProxy.yaml
  kroxylicious-operator/src/test/resources-filtered/DerivedResourcesTest/filter-resource-not-found/out-Deployment-example.yaml
  kroxylicious-operator/src/test/resources-filtered/DerivedResourcesTest/filter-resource-not-found/out-Secret-example.yaml
  kroxylicious-operator/src/test/resources-filtered/DerivedResourcesTest/filter-resource-not-found/out-Service-bar.yaml
  kroxylicious-operator/src/test/resources-filtered/DerivedResourcesTest/minimal/in-KafkaProxy.yaml
  kroxylicious-operator/src/test/resources-filtered/DerivedResourcesTest/minimal/out-Deployment-minimal.yaml
  kroxylicious-operator/src/test/resources-filtered/DerivedResourcesTest/minimal/out-Secret-minimal.yaml
  kroxylicious-operator/src/test/resources-filtered/DerivedResourcesTest/minimal/out-Service-one.yaml
  kroxylicious-operator/src/test/resources-filtered/DerivedResourcesTest/two-clusters/in-KafkaProxy.yaml
  kroxylicious-operator/src/test/resources-filtered/DerivedResourcesTest/two-clusters/out-Deployment-twocluster.yaml
  kroxylicious-operator/src/test/resources-filtered/DerivedResourcesTest/two-clusters/out-Secret-twocluster.yaml
  kroxylicious-operator/src/test/resources-filtered/DerivedResourcesTest/two-clusters/out-Service-bar.yaml
  kroxylicious-operator/src/test/resources-filtered/DerivedResourcesTest/two-clusters/out-Service-foo.yaml
  kroxylicious-operator/src/test/resources-filtered/DerivedResourcesTest/two-filters/in-Filter-filter-one.yaml
  kroxylicious-operator/src/test/resources-filtered/DerivedResourcesTest/two-filters/in-Filter-filter-two.yaml
  kroxylicious-operator/src/test/resources-filtered/DerivedResourcesTest/two-filters/in-KafkaProxy.yaml
  kroxylicious-operator/src/test/resources-filtered/DerivedResourcesTest/two-filters/out-Deployment-example.yaml
  kroxylicious-operator/src/test/resources-filtered/DerivedResourcesTest/two-filters/out-Secret-example.yaml
  kroxylicious-operator/src/test/resources-filtered/DerivedResourcesTest/two-filters/out-Service-foo.yaml
  kroxylicious-operator/src/test/resources-filtered/DerivedResourcesTest/use-pod-template-spec/in-KafkaProxy.yaml
  kroxylicious-operator/src/test/resources-filtered/DerivedResourcesTest/use-pod-template-spec/out-Deployment-use-pod-template-spec.yaml
  kroxylicious-operator/src/test/resources-filtered/DerivedResourcesTest/use-pod-template-spec/out-Secret-use-pod-template-spec.yaml
  kroxylicious-operator/src/test/resources-filtered/DerivedResourcesTest/use-pod-template-spec/out-Service-one.yaml
  pom.xml
Labels: release-process, operator

#1761 SNI exposition: user can control advertised broker port
  CHANGELOG.md
  kroxylicious-integration-test-support/src/main/java/io/kroxylicious/test/tester/KroxyliciousConfigUtils.java
  kroxylicious-integration-test-support/src/test/java/io/kroxylicious/proxy/config/ConfigurationTest.java
  kroxylicious-integration-tests/pom.xml
  kroxylicious-integration-tests/src/test/java/io/kroxylicious/net/PassthroughProxy.java
  kroxylicious-integration-tests/src/test/java/io/kroxylicious/net/PassthroughProxyTest.java
  kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/ExpositionIT.java
  kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/clusternetworkaddressconfigprovider/BrokerAddressPatternUtils.java
  kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/clusternetworkaddressconfigprovider/SniRoutingClusterNetworkAddressConfigProvider.java
  kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/filter/BrokerAddressFilter.java
  kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/model/VirtualCluster.java
  kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/service/ClusterNetworkAddressConfigProvider.java
  kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/KafkaProxyTest.java
  kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/config/ConfigParserTest.java
  kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/internal/clusternetworkaddressconfigprovider/SniRoutingClusterNetworkAddressConfigProviderTest.java
  kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/internal/filter/BrokerAddressFilterTest.java
  kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/model/VirtualClusterTest.java
  kroxylicious-runtime/src/test/resources/io/kroxylicious/proxy/internal/filter/DescribeCluster.test.yaml
  kroxylicious-runtime/src/test/resources/io/kroxylicious/proxy/internal/filter/Fetch.test.yaml
  kroxylicious-runtime/src/test/resources/io/kroxylicious/proxy/internal/filter/FindCoordinator.test.yaml
  kroxylicious-runtime/src/test/resources/io/kroxylicious/proxy/internal/filter/Metadata.test.yaml
  kroxylicious-runtime/src/test/resources/io/kroxylicious/proxy/internal/filter/Produce.test.yaml
  kroxylicious-runtime/src/test/resources/io/kroxylicious/proxy/internal/filter/ShareAcknowledge.test.yaml
  kroxylicious-runtime/src/test/resources/io/kroxylicious/proxy/internal/filter/ShareFetch.test.yaml
  kubernetes-examples/network-topologies/snirouting_tls/base/kroxylicious/kroxylicious-config.yaml
  kubernetes-examples/network-topologies/snirouting_tls_in_cluster/base/kroxylicious/kroxylicious-config.yaml
Labels: runtime, network, operator

#1743 Apply TLS protocol and ciphersuite restrictions to HTTP Clients used by KMS impls
  CHANGELOG.md
  kroxylicious-kms-provider-aws-kms/src/main/java/io/kroxylicious/kms/provider/aws/kms/AwsKms.java
  kroxylicious-kms-provider-aws-kms/src/main/java/io/kroxylicious/kms/provider/aws/kms/AwsKmsService.java
  kroxylicious-kms-provider-aws-kms/src/main/java/io/kroxylicious/kms/provider/aws/kms/config/Config.java
  kroxylicious-kms-provider-aws-kms/src/test/java/io/kroxylicious/kms/provider/aws/kms/AwsKmsServiceTest.java
  kroxylicious-kms-provider-fortanix-dsm/src/main/java/io/kroxylicious/kms/provider/fortanix/dsm/FortanixDsmKms.java
  kroxylicious-kms-provider-fortanix-dsm/src/main/java/io/kroxylicious/kms/provider/fortanix/dsm/FortanixDsmKmsService.java
  kroxylicious-kms-provider-fortanix-dsm/src/main/java/io/kroxylicious/kms/provider/fortanix/dsm/config/Config.java
  kroxylicious-kms-provider-fortanix-dsm/src/test/java/io/kroxylicious/kms/provider/fortanix/dsm/FortanixDsmKmsServiceTest.java
  kroxylicious-kms-provider-hashicorp-vault/src/main/java/io/kroxylicious/kms/provider/hashicorp/vault/VaultKms.java
  kroxylicious-kms-provider-hashicorp-vault/src/main/java/io/kroxylicious/kms/provider/hashicorp/vault/VaultKmsService.java
  kroxylicious-kms-provider-hashicorp-vault/src/main/java/io/kroxylicious/kms/provider/hashicorp/vault/config/Config.java
  kroxylicious-kms-provider-hashicorp-vault/src/test/java/io/kroxylicious/kms/provider/hashicorp/vault/TestVault.java
  kroxylicious-kms-provider-hashicorp-vault/src/test/java/io/kroxylicious/kms/provider/hashicorp/vault/VaultKmsServiceTest.java
  kroxylicious-kms-provider-hashicorp-vault/src/test/java/io/kroxylicious/kms/provider/hashicorp/vault/VaultKmsTest.java
  kroxylicious-kms-provider-hashicorp-vault/src/test/java/io/kroxylicious/kms/provider/hashicorp/vault/VaultKmsTlsIT.java
  kroxylicious-kms-provider-hashicorp-vault/src/test/java/io/kroxylicious/kms/provider/hashicorp/vault/config/ConfigParseTest.java
  kroxylicious-kms-tls-support/pom.xml
  kroxylicious-kms-tls-support/src/main/java/io/kroxylicious/proxy/tls/InsecureTrustManager.java
  kroxylicious-kms-tls-support/src/main/java/io/kroxylicious/proxy/tls/TlsHttpClientConfigurator.java
  kroxylicious-kms-tls-support/src/test/java/io/kroxylicious/proxy/tls/JdkTlsTest.java
  kroxylicious-kms-tls-support/src/test/java/io/kroxylicious/proxy/tls/TlsHttpClientConfiguratorTest.java
Labels: filter: record-encryption, security

#1763 Document advertisedBrokerAddressPattern
  docs/modules/configuring/con-configuring-network-addresses.adoc
  docs/modules/configuring/ref-configuring-proxy-example.adoc
Labels: documentation, runtime

#1716 Docs for per cluster filters
  docs/assemblies/assembly-configuring-proxy.adoc
  docs/modules/configuring/con-configuration-outline.adoc
  docs/modules/configuring/con-configuring-filters.adoc
  docs/modules/configuring/con-configuring-toplevel-other-settings.adoc
  docs/modules/configuring/con-configuring-vc-client-tls.adoc
  docs/modules/configuring/con-configuring-vc-network-addresses.adoc
  docs/modules/configuring/con-configuring-vc-other-settings.adoc
  docs/modules/configuring/con-configuring-vc-target-tls.adoc
  docs/modules/configuring/ref-configuring-proxy-example.adoc
Labels: documentation, configuration api

#1776 Jacoco PR coverage recording fix
  pom.xml
Labels: build

#1775 docs(bug): fixes broken link related to github issues
  docs/_assets/attributes.adoc
  docs/assemblies/assembly-multi-tenancy-filter.adoc
  docs/modules/configuring/con-configuring-vc-client-tls.adoc
Labels: documentation

#1782 Fortanix DSM KMS - developer instructions and CI integration
  .github/AUTOMATION_README.md
  kroxylicious-kms-provider-fortanix-dsm/DEV_GUIDE.md
Labels: documentation, filter: record-encryption
