Repository kroxylicious/kroxylicious, pull requests merged in 2025-08, with the labels that each got.

#2517 fix(docs) align metric names with those actually in use
  docs/_modules/monitoring/con-prometheus-metrics-proxy.adoc
Labels: documentation

#2522 bugfix: asset signatures not attached to release
  scripts/stage-release.sh
Labels: kind/bug, dev/release

#2524 Update stage-docs.sh for new documentation release flow
  scripts/stage-docs.sh
Labels: documentation, dev/release

#2537 Build and load operand image into minikube before operator tests
  .github/workflows/operator-maven.yaml
Labels: kind/bug, dev/github_actions

#2546 chore: remove superfluous dependencyManagement declaration (enforcer-…
  pom.xml
Labels: dev/maven

#2536 Describe release token requirements in releasing instructions
  .github/workflows/promote_release.yaml
  .github/workflows/stage_release.yaml
  RELEASING.md
Labels: documentation, dev/github_actions

#2559 Fix quick start proxy port
  docs/proxy-quick-start/index.adoc
Labels: kind/bug, documentation

#2518 feat(docs): quickstart guide for record encryption on Kubernetes
  CHANGELOG.md
  docs/_assets/attributes.adoc
  docs/_assets/quickstart-record-encryption.excalidraw
  docs/_modules/record-validation/con-example-proxy-config.adoc
  docs/images/quickstart-record-encryption.svg
  docs/record-encryption-quickstart/_assets
  docs/record-encryption-quickstart/doc.yaml
  docs/record-encryption-quickstart/images
  docs/record-encryption-quickstart/index.adoc
  kroxylicious-operator/packaging/examples/record-encryption/03.Filter.encryption.yaml
Labels: documentation

#2574 docs(olm): instructions for deploying operator using OLM
  docs/_assemblies/assembly-operator-install.adoc
  docs/_modules/install/proc-install-operator-olm.adoc
  docs/_modules/install/proc-install-operator.adoc
Labels: documentation

#2600 fix: doc processing plugins (webify etc) should not inherit to other modules.
  pom.xml
Labels: kind/bug, documentation, dev/maven

#2605 refactor: use java to build the operand image for the operator test Github workflow
  .github/workflows/operator-maven.yaml
Labels: dev/maven, kind/refactoring

#2598 Enhancement: Active Connections Gauge
  .gitignore
  CHANGELOG.md
  kroxylicious-docs/docs/_modules/monitoring/con-prometheus-metrics-proxy.adoc
  kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/MetricsIT.java
  kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/MeterRegistries.java
  kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java
  kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/util/ActivationToken.java
  kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/util/Metrics.java
  kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/util/VirtualClusterNode.java
  kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachineTest.java
  kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/internal/util/ActivationTokenTest.java
Labels: kind/enhancement, runtime, observability

#2595 Test framework to subject codeblocks (yaml, shell) embedded in Asciidoc files to validations specified in Junit
  .github/workflows/documentation-tests.yml
  .github/workflows/maven.yaml
  .github/workflows/operator-maven.yaml
  kroxylicious-docs-tests/pom.xml
  kroxylicious-docs-tests/src/main/java/io/kroxylicious/doctools/asciidoc/AdocConverter.java
  kroxylicious-docs-tests/src/main/java/io/kroxylicious/doctools/asciidoc/AdocNodeConverter.java
  kroxylicious-docs-tests/src/main/java/io/kroxylicious/doctools/asciidoc/Block.java
  kroxylicious-docs-tests/src/main/java/io/kroxylicious/doctools/asciidoc/BlockExtractor.java
  kroxylicious-docs-tests/src/test/java/io/kroxylicious/doctools/asciidoc/AdocConverterTest.java
  kroxylicious-docs-tests/src/test/java/io/kroxylicious/doctools/asciidoc/BlockExtractorTest.java
  kroxylicious-docs-tests/src/test/java/io/kroxylicious/doctools/validator/QuickstartDT.java
  kroxylicious-docs-tests/src/test/java/io/kroxylicious/doctools/validator/Utils.java
  kroxylicious-docs-tests/src/test/java/io/kroxylicious/doctools/validator/YamlCodeblockValidationDT.java
  kroxylicious-docs-tests/src/test/resources/sample-with-html-entities.adoc
  kroxylicious-docs-tests/src/test/resources/sample.adoc
  kroxylicious-docs/docs/record-encryption-quickstart/index.adoc
  kroxylicious-integration-test-support/pom.xml
  kroxylicious-integration-test-support/src/main/java/io/kroxylicious/test/ShellUtils.java
  kroxylicious-operator/pom.xml
  kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/AbstractInstallKT.java
  kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/KindInstallKT.java
  kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/MinikubeInstallKT.java
  kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/OcInstallKT.java
  pom.xml
  scripts/extract-codeblock.awk
  scripts/extract-yaml-fencedcodeblocks.sh
Labels: documentation
